mailProvider: snailgun

mailgunApiKey: ${DW_MAILGUN_API_KEY:-}
sendgridApiKey: ${DW_SENDGRID_API_KEY:-}
spendgridApiKey: api_key_WeIff2IQtXguwRi3E54gar0Q
snailgunApiKey: api_key_lrEG1Pkn6mN1SVnKpFFO6HAB

swagger:
  resourcePackage: com.mailit.resources
  title: Mail It
  schemes: [https, http]

logging:
  level: INFO
  loggers:
    com.mailit: DEBUG
